name = "DFD Hugo Minimal Test"
copyright = "© 2021-2023 Wild Tech 'Garden'"
description = "Module for WTG's Hugo minimal test theme"

[module]
[module.hugoVersion]
min = "0.115.3"
extended = false

# Note that this is no longer used.
[author]
name = "Daniel F. Dickinson for Wild Tech 'Garden'"
homepage = "https://www.wildtechgarden.ca/"
copyright = "© 2021-2023 Wild Tech 'Garden'"
email = "dfdpublic@wildtechgarden.ca"
