name = "Hugo Minimal Test Theme"
copyright = "© 2021-2022 Daniel F. Dickinson"
license = "MIT"
licenselink = "https://github.com/danielfdickinson/minimal-test-theme-hugo-dfd/blob/main/LICENSE"
description = "A minimal theme to demo/test Hugo modules."
homepage = "https://minimal-test-theme.wildtechgarden.ca/"
tags = ["test","minimal","light","minimalist","fast","demo"]
features = ["light","fast","debugging tool"]
min_version = "0.80.0"
extended = false
summaryLength = "25"

[author]
name = "Daniel F. Dickinson"
homepage = "https://wildtechgarden.ca/about/"
copyright = "© 2021-2022 Daniel F. Dickinson"
email = "dfdpublic@wildtechgarden.ca"
