name = "Hugo minimal test theme"
copyright = "© 2021-2023 Wild Tech 'Garden'"
license = "MIT"
licenselink = "https://github.com/wildtechgarden/minimal-test-theme-hugo-wtg/blob/main/LICENSE"
description = "A minimal theme to demo/test Hugo modules."
homepage = "https://www.minimal-test-theme.wtg-demos.ca/"
tags = ["test","minimal","light","minimalist","fast","demo"]
features = ["light","fast","minimal"]
min_version = "0.115.3"
extended = false
summaryLength = "25"

[author]
name = "Daniel F. Dickinson for Wild Tech 'Garden'"
homepage = "https://wildtechgarden.ca/about/"
copyright = "© 2021-2023 Wild Tech 'Garden'"
email = "dfdpublic@wildtechgarden.ca"
