baseURL = "https://www.minimal-test-theme.wtg-demos.ca/"
copyright = "© 2021-2023 Wild Tech 'Garden'"
homepage = "https://www.minimal-test-theme.wtg-demos.ca/"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableGitInfo = true
enableRobotsTXT = false
summaryLength = 25
disableKinds = ["RSS","sitemap"]

[params]
mainSections = ["post"]
# For demo/sample sites we default to not being canonical
pageCanonical = false
redirectsDomains = [
	"http://minimal-test-theme.netlify.app/* https://minimal-test-theme.demo.wildtechgarden.ca/:splat 301!",
	"https://minimal-test-theme.netlify.app/* https://minimal-test-theme.demo.wildtechgarden.ca/:splat 301!",
	"http://minimal-test-theme.wildtechgarden.ca/* https://minimal-test-theme.demo.wildtechgarden.ca/:splat 301!"
]
staticFallback = false
# Disable if you don't want the test (bare-bones) CSS
testStylesInclude = true
# Footnotes and TableOfContents don't work properly with a base href set in <head>
useBaseURL = false

[outputFormats]
[outputFormats.nredirects]
baseName = "_redirects"
isPlainText = true
mediaType = "text/nredirects"

[mediaTypes]
[mediaTypes."text/nredirects"]
suffixes = [""]

[outputs]
home = ["HTML", "RSS", "nredirects"]

# See https://gohugo.io/content-management/multilingual/
# and https://www.regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/

[languages]
[languages.fr]
title = "Hugo thème du teste minimale"
weight = 10
contentDir = "content/fr"

[languages.fr.params]
description = "Demo site au Hugo thème du teste minimal du Wild Tech 'Garden' (WTG)"

[languages.fr.menu]
[[languages.fr.menu.main]]
identifier = "about"
name = "À propos"
pageref = "readme"
weight = 10

[[languages.fr.menu.main]]
identifier = "l'accessibilité"
name = "L'accessibilité"
pageref = "accessibility"
weight = 20

[languages.en]
title = "Hugo minimal test theme"
weight = 1
contentDir = "content/en"

[languages.en.params]
description = "Demo site for Wild Tech 'Garden's (WTG) Hugo minimal test theme"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
pageref = "readme"
weight = 10

[[languages.en.menu.main]]
identifier = "accessibility"
name = "Accessibility"
pageref = "accessibility"
weight = 20

[taxonomies]
tag = "tags"

[frontmatter]
lastmod = [":git", "lastmod", ":fileModTime", "date", "publishDate"]

[markup]
[markup.highlight]
guessSyntax = true
noClasses = false

[markup.goldmark]
[markup.goldmark.parser]
autoHeadingIDType = "github-ascii"

[privacy]

[privacy.vimeo]
disabled = true

[privacy.twitter]
disabled = true

[privacy.instagram]
disabled = true

[privacy.youtube]
disabled = true

[module]
# For the example site, we need the _current_ theme module from the same repo (path is relative to themes directory)
# See https://gohugo.io/hugo-modules/configuration/#module-config-top-level (replacements)
replacements = "github.com/wildtechgarden/minimal-test-theme-hugo-wtg -> ../.."

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "data"
target = "data"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "i18n"
target = "i18n"

[[module.mounts]]
source = "archetypes"
target = "archetypes"

[[module.mounts]]
source = "content/en"
target = "content"
lang = "en"

[[module.mounts]]
source = "content/fr"
target = "content"
lang = "fr"

[[module.imports]]
path = "github.com/wildtechgarden/minimal-test-theme-hugo-wtg"

[[module.imports.mounts]]
source = "static"
target = "static"

[[module.imports.mounts]]
source = "layouts"
target = "layouts"

[[module.imports.mounts]]
source = "data"
target = "data"

[[module.imports.mounts]]
source = "assets"
target = "assets"

[[module.imports.mounts]]
source = "i18n"
target = "i18n"

[[module.imports.mounts]]
source = "archetypes"
target = "archetypes"

[[module.imports.mounts]]
source = "README.md"
target = "content/README.md"
lang = "en"

[[module.imports.mounts]]
source = "README.fr.md"
target = "content/README.md"
lang = "fr"

[[module.imports.mounts]]
source = "docs"
target = "content/docs"
lang = "en"

[[module.imports.mounts]]
source = "docs"
target = "content/docs"
lang = "fr"

[[module.imports.mounts]]
source = "LICENSE"
target = "content/LICENSE"
lang = "en"

[[module.imports.mounts]]
source = "LICENSE"
target = "content/LICENSE"
lang = "fr"
