---
name: build-and-deploy
# Assumes status checks have passed on a *required* pull request
# If you don't use that configuration you will have no CI as this
# workflow does not test (since the tests should already have passed).)
on: # yamllint disable-line
  push:
    branches:
      - main
jobs:
  build-deploy-site:
    runs-on: ubuntu-20.04
    environment: production
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    steps:
      - name: "Build Site with Hugo and Audit"
        uses: danielfdickinson/build-audit-action-hugo-dfd@main
        with:
          build-for-downstream: "true"
          do-minify-bundle: "true"
          use-lfs: false
          source-directory: exampleSite
      - name: "Install Rclone"
        run: |
          sudo apt-get update
          sudo apt-get install rclone
      - name: "Deploy minified site (rclone sync)"
        shell: bash
        env:
          RCLONE_ONE_FILE_SYSTEM: "true"
          RCLONE_ERROR_ON_NO_TRANSFER: "true"
          RCLONE_SFTP_SKIP_LINKS: "true"
          RCLONE_SFTP_KEY_FILE_PASS: "${{ secrets.DEPLOY_SFTP_KEY_PASS }}"
          RCLONE_SFTP_PORT: ${{ secrets.DEPLOY_SFTP_PORT }}
          RCLONE_SFTP_HOST: ${{ secrets.DEPLOY_SFTP_HOSTNAME }}
          SFTP_KEY_PEM: "${{ secrets.DEPLOY_SFTP_PRIVATE_KEY }}"
          REMOTE_PATH: "${{ secrets.DEPLOY_SFTP_REMOTE_PATH }}"
          RCLONE_SFTP_USER: ${{ secrets.DEPLOY_SFTP_USERNAME }}
          # yamllint disable rule:line-length
        run: |
          eval "$(ssh-agent)"
          umask 177
          echo "${SFTP_KEY_PEM}" >~/sftp-key-file
          umask 0022
          export RCLONE_SFTP_KEY_FILE=~/sftp-key-file
          export RCLONE_ONE_FILE_SYSTEM RCLONE_ERROR_ON_NO_TRANSFER RCLONE_SFTP_SKIP_LINKS RCLONE_SFTP_KEY_FILE_PASS RCLONE_SFTP_PORT RCLONE_SFTP_HOST REMOTE_PATH RCLONE_SFTP_USER
          rclone sync public/ :sftp:${REMOTE_PATH}
        # yamllint enable
