---
name: build-and-deploy
# Assumes status checks have passed on a *required* pull request
# If you don't use that configuration you will have no CI as this
# workflow does not test (since the tests should already have passed).)
on: # yamllint disable-line
  push:
    branches:
      - main
jobs:
  build-deploy-site:
    runs-on: ubuntu-20.04
    environment: umbrella-tsi
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    steps:
      - name: "Build Site with Hugo and Audit"
        uses: danielfdickinson/build-audit-action-hugo-dfd@v0.3
        with:
          base-url: "https://test-umbrella.wildtechgarden.ca/minimal-test-theme/"
          build-for-downstream: "true"
          config-file: exampleSite/config.toml
          do-minify-bundle: "true"
          source-directory: exampleSite
          use-lfs: false
      - name: Install Rclone
        run: |
          sudo apt-get update
          sudo apt-get install rclone
      - name: Deploy sub-site (rclone sync)
        shell: bash
        env:
          RCLONE_ONE_FILE_SYSTEM: "true"
          RCLONE_ERROR_ON_NO_TRANSFER: "true"
          RCLONE_FTP_EXPLICIT_TLS: "true"
          RCLONE_FTP_PASS: ${{ secrets.DEPLOY_FTP_PASS }}
          RCLONE_FTP_PORT: ${{ secrets.DEPLOY_FTP_PORT }}
          RCLONE_FTP_HOST: ${{ secrets.DEPLOY_FTP_HOSTNAME }}
          REMOTE_PATH: ${{ secrets.DEPLOY_FTP_REMOTE_PATH }}
          RCLONE_FTP_USER: ${{ secrets.DEPLOY_FTP_USERNAME }}
        run: |
          export RCLONE_ONE_FILE_SYSTEM RCLONE_ERROR_ON_NO_TRANSFER RCLONE_FTP_PASS RCLONE_FTP_PORT RCLONE_FTP_HOST REMOTE_PATH RCLONE_FTP_USER
          rclone sync public/ :ftp:${REMOTE_PATH}
...
