---
# yamllint disable rule:key-ordering
name: monthly-external-link-check
on: # yamllint disable-line
  schedule:
  #  # At 1:40 AM -0500 on the 28th of each month strictly check all links
  #  (301 Moved is a failure not just a warning)
  - cron: 40 6 28 * *

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-unminified-site:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build site with Hugo and audit
      uses: danielfdickinson/build-audit-action-hugo-dfd@v0.3
      with:
        base-url: "https://test-umbrella.wildtechgarden.ca/minimal-test-theme/"
        build-for-downstream: "true"
        config-file: exampleSite/config.toml
        use-lfs: false
        source-directory: exampleSite
    - name: Validate exampleSite HTML
      uses: danielfdickinson/validate-html-action-hugo-dfd@v0.3
      with:
        action-workspace: ${{ github.workspace }}
        use-existing-workspace: "true"
    - name: Strict check of all links
      uses: danielfdickinson/link-check-action-hugo-dfd@v0.3
      with:
        canonical-root: "https://test-umbrella.wildtechgarden.ca/minimal-test-theme/" # yamllint disable-line
        check-external: true
        check-external-strict: true
        entry-point: index.html
        upload-logs-as: weekly-external-check-failure
        upload-logs-retention: 4
        use-existing-workspace: "true"
...
